<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Godsgift Braimah, Devon Vorster, Chikire Aku-Ibe, &amp; Fu Hung Kwong">

<title>Predicting Whether Clients Will Subscribe To A Term Deposit Based On Their Information.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="term-deposit-analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="term-deposit-analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="term-deposit-analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="term-deposit-analysis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="term-deposit-analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="term-deposit-analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="term-deposit-analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="term-deposit-analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="term-deposit-analysis_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="term-deposit-analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="term-deposit-analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="term-deposit-analysis_files/libs/bootstrap/bootstrap-401e8839002e47774de535522c240817.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary:</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction:</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods:</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data:</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis:</a></li>
  </ul></li>
  <li><a href="#results-discussion" id="toc-results-discussion" class="nav-link" data-scroll-target="#results-discussion">Results &amp; Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References:</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../index.html.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Whether Clients Will Subscribe To A Term Deposit Based On Their Information.</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Godsgift Braimah, Devon Vorster, Chikire Aku-Ibe, &amp; Fu Hung Kwong </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="summary" class="level1">
<h1>Summary:</h1>
<p>We built a classification model using the Support Vector Classifier (SVC), which can utilise information related to the client and the marketing contact to predict whether a client will subscribe to a term deposit. Our folder structure and code guide were adapted from Tiffany A. Timbers, Joel Ostblom &amp; Melissa Lee <span class="citation" data-cites="Timbers_breast_cancer_repo">(<a href="#ref-Timbers_breast_cancer_repo" role="doc-biblioref">Timbers n.d.</a>)</span></p>
<p>Our classifier, the SVC, performed well on an unseen test data set, achieving a Test Score (Accuracy) of <strong>0.9075</strong>. Its Train Score indicated a good fit without significant overfitting. Although the simple accuracy score does not detail the balance of True Positives versus False Negatives, an accuracy exceeding <strong>80%</strong> suggests the model is highly effective.</p>
<p>Given our goal is to increase the subscription rate, the model’s primary goal is to minimize the False Negative rate, avoiding the error of predicting a client will not subscribe when they would have. The current performance suggests that using this model for initial client prioritization could significantly improve resource allocation, making the model valuable for immediate business implementation. However, further analysis of precision and recall would be necessary to optimize its practical utility.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction:</h1>
<p>Direct marketing campaigns, particularly those relying on phone calls, are a significant investment for banking institutions. The success of these campaigns is measured by the client subscription rate to a product like a term deposit. Another dataset shows that the subscription rate of term deposit in a Portuguese banking is only around 11.70% <span class="citation" data-cites="Ngu_2024">(<a href="#ref-Ngu_2024" role="doc-biblioref">Ngu 2024</a>)</span>, optimizing the targeting strategy is crucial to maximize return on investment and minimize operational costs.</p>
<p>Here we ask if a machine learning algorithm can be used to predict whether a client will subscribe to a term deposit based on information related to the client, such as type of job, education level; and also the marketing contact, e.g.&nbsp;number of contacts during the campaign, number of days since last contact. Answering this question is important because term deposit campaigns often require multiple contacts to the same client, making the process labor-intensive and expensive. Thus, if a machine learning algorithm can accurately and effectively predict client subscription, this could allow the bank to prioritize clients who are most likely to convert, leading to more efficient resource allocation and a higher overall subscription rate, improving the campaign results.</p>
</section>
<section id="methods" class="level1">
<h1>Methods:</h1>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data:</h2>
<p>The data we used was obtained the UCI Machine Learning Repository which can be found <span class="citation" data-cites="ucimlrepo_2025">(<a href="#ref-ucimlrepo_2025" role="doc-biblioref">uci-ml-repo 2025</a>)</span>, specifically the Bank Marketing dataset of a Portuguese bank institution . The dataset contains various features about bank customers and whether they subscribed to a term deposit, an investment product offered by the bank (variable y). Each row in the dataset contains details of customers which was used to predict if they would subscribe to the term deposit or not. The original dataset contains 45211 records with 16 features and one target (17 columns). For the purpose of this analysis, we sampled 4,000 records from the original dataset to speed up the EDA and model training process.</p>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis:</h2>
<p>We started this analysis by performing an exploratory data analysis (EDA) to understand the nature of the variables and their relationships. We observed some missing values in the dataset. We also observed that the target variable (y) was imbalanced with a higher proportion of customers not subscribing to the term deposit.</p>
<p>We decided to use Support Vector Classifier (SVC) models for this analysis.The <span class="citation" data-cites="scikit_learn">(<a href="#ref-scikit_learn" role="doc-biblioref">Scikit-learn n.d.</a>)</span> package was greatly used in these processes. We performed hyperparameter tuning using Python RandomizedSearchCV to find the best parameters for each model. We mapped the values of the target y, using ‘yes’: 1, ‘no’: 0. The data was split using 80% for the training set and 20% for the test set. In the preprocessing, we dropped ‘day_of_week’ and ‘pdays’ because we considered them not relevant for analysis. The ‘poutcome’ variable was also dropped since it had a high number of missing values. Categorical variables were one-hot encoded, ordinal data were handled using ordinal encoding, numerical variables were scaled using StandardScaler and missing values for the selected features were imputed using SimpleImputer with the “most frequent” strategy.</p>
<p>The models were evaluated based on their accuracy on the test set.</p>
<section id="loading-the-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-the-data">Loading The Data</h3>
<div class="cell" data-execution_count="2">
<div id="tbl-banking-sample-data" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-banking-sample-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Banking Sample Data.
</figcaption>
<div aria-describedby="tbl-banking-sample-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">job</th>
<th data-quarto-table-cell-role="th">marital</th>
<th data-quarto-table-cell-role="th">education</th>
<th data-quarto-table-cell-role="th">default</th>
<th data-quarto-table-cell-role="th">balance</th>
<th data-quarto-table-cell-role="th">housing</th>
<th data-quarto-table-cell-role="th">loan</th>
<th data-quarto-table-cell-role="th">contact</th>
<th data-quarto-table-cell-role="th">day_of_week</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">duration</th>
<th data-quarto-table-cell-role="th">campaign</th>
<th data-quarto-table-cell-role="th">pdays</th>
<th data-quarto-table-cell-role="th">previous</th>
<th data-quarto-table-cell-role="th">poutcome</th>
<th data-quarto-table-cell-role="th">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">30577</th>
<td>42</td>
<td>technician</td>
<td>married</td>
<td>tertiary</td>
<td>no</td>
<td>1397</td>
<td>yes</td>
<td>no</td>
<td>cellular</td>
<td>6</td>
<td>feb</td>
<td>135</td>
<td>7</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">30048</th>
<td>51</td>
<td>blue-collar</td>
<td>married</td>
<td>secondary</td>
<td>no</td>
<td>362</td>
<td>yes</td>
<td>yes</td>
<td>cellular</td>
<td>4</td>
<td>feb</td>
<td>318</td>
<td>3</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">24147</th>
<td>23</td>
<td>admin.</td>
<td>single</td>
<td>secondary</td>
<td>no</td>
<td>40</td>
<td>no</td>
<td>no</td>
<td>telephone</td>
<td>10</td>
<td>nov</td>
<td>1239</td>
<td>1</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">25584</th>
<td>57</td>
<td>entrepreneur</td>
<td>married</td>
<td>tertiary</td>
<td>no</td>
<td>1828</td>
<td>yes</td>
<td>no</td>
<td>cellular</td>
<td>19</td>
<td>nov</td>
<td>68</td>
<td>1</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">15822</th>
<td>47</td>
<td>management</td>
<td>divorced</td>
<td>tertiary</td>
<td>no</td>
<td>2105</td>
<td>no</td>
<td>yes</td>
<td>cellular</td>
<td>21</td>
<td>jul</td>
<td>363</td>
<td>1</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">177</th>
<td>34</td>
<td>technician</td>
<td>married</td>
<td>secondary</td>
<td>no</td>
<td>51</td>
<td>yes</td>
<td>no</td>
<td>NaN</td>
<td>5</td>
<td>may</td>
<td>19</td>
<td>2</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">20421</th>
<td>44</td>
<td>self-employed</td>
<td>married</td>
<td>primary</td>
<td>no</td>
<td>4</td>
<td>no</td>
<td>no</td>
<td>cellular</td>
<td>12</td>
<td>aug</td>
<td>327</td>
<td>2</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7170</th>
<td>26</td>
<td>admin.</td>
<td>single</td>
<td>tertiary</td>
<td>no</td>
<td>3672</td>
<td>yes</td>
<td>no</td>
<td>NaN</td>
<td>29</td>
<td>may</td>
<td>360</td>
<td>5</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">928</th>
<td>52</td>
<td>blue-collar</td>
<td>married</td>
<td>secondary</td>
<td>no</td>
<td>-98</td>
<td>yes</td>
<td>no</td>
<td>NaN</td>
<td>7</td>
<td>may</td>
<td>423</td>
<td>1</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">20114</th>
<td>35</td>
<td>technician</td>
<td>single</td>
<td>tertiary</td>
<td>no</td>
<td>2277</td>
<td>no</td>
<td>yes</td>
<td>cellular</td>
<td>11</td>
<td>aug</td>
<td>55</td>
<td>2</td>
<td>-1</td>
<td>0</td>
<td>NaN</td>
<td>no</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-banking-sample-data" class="quarto-xref">Table&nbsp;1</a> shows the first ten rows of our sample data.</p>
</section>
<section id="data-validation" class="level3">
<h3 class="anchored" data-anchor-id="data-validation">Data Validation</h3>
<p>During our data valuation, we checked the following:</p>
<ol type="1">
<li>Correct data file format</li>
<li>Correct column names</li>
<li>No empty observations</li>
<li>Missingness not beyond expected threshold</li>
<li>Correct data types in each column</li>
<li>No duplicate observations</li>
<li>No outlier or anomalous values</li>
<li>Correct category levels (i.e., no string mismatches or single values)</li>
<li>Target/response variable follows expected distribution</li>
<li>No anomalous correlations between target/response variable and features/explanatory variables</li>
<li>No anomalous correlations between features/explanatory variables</li>
</ol>
<p>After our checks, we observed that our data had the correct data file format, correct column names, no empty observations, no missingness beyond expected threshold, correct data types in each column, and no duplicate observations.</p>
</section>
<section id="eda" class="level3">
<h3 class="anchored" data-anchor-id="eda">EDA</h3>
<div id="fig-univariate-num" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-univariate-num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/numeric_univariate.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-univariate-num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Univariate distributions of numeric variables in Bank Marketing Dataset
</figcaption>
</figure>
</div>
<p>Our distribution plots for variables previous, pday, campaign, duration, balance in <a href="#fig-univariate-num" class="quarto-xref">Figure&nbsp;1</a> were highly right-skewed.</p>
<div id="fig-univariate-cat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-univariate-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/categorical_univariate.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-univariate-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Univariate distributions of Categorical variables in Bank Marketing Dataset
</figcaption>
</figure>
</div>
<div id="fig-correlation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/correlation_plot.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Correlation Plots For Numeric variables in Bank Marketing Dataset
</figcaption>
</figure>
</div>
<p>This implies that most customers had low values for these variables and a few customers had high values. In addition, the correlation plots in <a href="#fig-correlation" class="quarto-xref">Figure&nbsp;3</a> showed that “previous” and “pday” had the highest positive correlation.</p>
</section>
<section id="data-preprocessing-model-building-and-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="data-preprocessing-model-building-and-evaluation">Data Preprocessing, Model Building and Evaluation</h3>
<p>We experimented on SVC and Logistic Regression models. We decided to train Support Vector Classifier (SVC) to determine which was more efficient in predicting if a customer would subscribed to the banks offering of term investments. We performed hyperparameter tuning using RandomizedSearchCV to find the best parameters for each model. The models were evaluated based on their accuracy on the test set.</p>
</section>
</section>
</section>
<section id="results-discussion" class="level1">
<h1>Results &amp; Discussion</h1>
<p>Our SVC train score can be seen in <a href="#tbl-train-score" class="quarto-xref">Table&nbsp;2</a> below:</p>
<div class="cell" data-execution_count="3">
<div id="tbl-train-score" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-train-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: SVC Train Score.
</figcaption>
<div aria-describedby="tbl-train-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">metric</th>
<th data-quarto-table-cell-role="th">score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>accuracy</td>
<td>0.9034</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Our SVC test score can be seen in <a href="#tbl-test-score" class="quarto-xref">Table&nbsp;3</a> below:</p>
<div class="cell" data-execution_count="4">
<div id="tbl-test-score" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-test-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: SVC Test Score.
</figcaption>
<div aria-describedby="tbl-test-score-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">metric</th>
<th data-quarto-table-cell-role="th">score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>accuracy</td>
<td>0.9075</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Our SVC classification model performed well on the testing data, with accuracy(test score) of 0.9075 and a training score of 0.9034.</p>
<p>Considering the imbalance in our target class, accuracy alone is not sufficient for determining the suitability of our model. Therefore, exploring metrics from the confusion matrix in <a href="#fig-confusion-matrix" class="quarto-xref">Figure&nbsp;4</a> and classification report is recommended as a next step.</p>
<div id="fig-confusion-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../results/figures/test_svc_confusion_matrix.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Confusion Matrix for SVC model
</figcaption>
</figure>
</div>
<div class="cell" data-execution_count="5">
<div id="tbl-classification-report" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classification-report-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: SVC Classification Report.
</figcaption>
<div aria-describedby="tbl-classification-report-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">precision</th>
<th data-quarto-table-cell-role="th">recall</th>
<th data-quarto-table-cell-role="th">f1-score</th>
<th data-quarto-table-cell-role="th">support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0.92</td>
<td>0.98</td>
<td>0.95</td>
<td>714.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0.67</td>
<td>0.28</td>
<td>0.39</td>
<td>86.00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">accuracy</th>
<td>0.91</td>
<td>0.91</td>
<td>0.91</td>
<td>0.91</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">macro avg</th>
<td>0.79</td>
<td>0.63</td>
<td>0.67</td>
<td>800.00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">weighted avg</th>
<td>0.89</td>
<td>0.91</td>
<td>0.89</td>
<td>800.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>However, <strong>relying solely on accuracy is misleading in this context</strong>. Further analysis of the classification report <a href="#tbl-classification-report" class="quarto-xref">Table&nbsp;4</a> reveals that the F1-scores and Recall scores, critical metrics for identifying the minority class (trem deposit subscribers) are suboptimal. The SVC model performed with a recall of <strong>0.91</strong> (F1: <strong>0.89</strong>). This discrepancy between high accuracy and low recall is a classic indicator of class imbalance, where the models are biased toward predicting the majority class (non-subscribers) at the expense of identifying potential subscribers .</p>
<p><strong>Model Selection:</strong> <br> For the purpose of this project, we will proceed with the SVC model, as it demonstrates superior predictive performance (higher F1 and Recall) compared to Logistic Regression. <strong>However, the current recall is still insufficient for a robust marketing strategy</strong>. To address this, future iterations of the model must prioritize techniques that specifically target the minority class. <br></p>
<p><strong>To improve the model’s ability to detect subscribers and extract actionable insights, we propose the following steps:</strong></p>
<ul>
<li><p><strong>Addressing Class Imbalance</strong>: To prevent the model from ignoring the minority class, we should incorporate class weighting (e.g., setting class_weight=‘balanced’ in sklearn) or apply resampling techniques such as SMOTE (Synthetic Minority Over-sampling Technique) to artificially balance the training data.</p></li>
<li><p><strong>Threshold Tuning via Precision-Recall or ROC Curves</strong>: The default decision threshold of 0.5 is likely too high for detecting rare events. By analyzing the Precision-Recall curve, we can identify a custom operating point (e.g., lowering the threshold to 0.1 or 0.2) that maximizes Recall, ensuring we miss fewer potential subscribers even if it results in slightly more false positives.</p></li>
<li><p><strong>Feature Selection with L1 Regularization</strong>: While SVC is our choice for prediction, we may utilize Lasso (L1 Regularization) as a supplementary analysis tool. L1 regularization induces sparsity by shrinking coefficients of irrelevant features to exactly zero. This would allow us to isolate the specific characteristics that drive subscriptions, providing the bank with a clear, interpretable list of features to focus their marketing efforts on.</p></li>
</ul>
<p>A second area for further analysis is determining which specific features are most important for predicting whether a client will subscribe to a term deposit. Identifying these key features will enable the bank to better tailor its actions to increase subscription rates. In light of this, the Logistic Regression model is a better choice, as it provides more interpretable results. However, due to interactions between features and preprocessing steps such as regularization, the coefficients of the Logistic Regression model can become difficult to interpret. Nevertheless, if properly examined, the coefficient estimates can help identify the important characteristics the bank should focus on to increase its rate of subscriptions to term deposits.</p>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References:</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Ngu_2024" class="csl-entry" role="listitem">
Ngu, H. E. 2024. <span>“Predictive Analysis of Client Subscription Rates in the Portuguese Banking Sector Using SAS.”</span> Medium. <a href="https://medium.com/@nguhe/predictive-analysis-of-client-subscription-rates-in-the-portuguese-banking-sector-using-sas-40fb04a9dcd3">https://medium.com/@nguhe/predictive-analysis-of-client-subscription-rates-in-the-portuguese-banking-sector-using-sas-40fb04a9dcd3</a>.
</div>
<div id="ref-scikit_learn" class="csl-entry" role="listitem">
Scikit-learn. n.d. <em>Scikit-Learn: Machine Learning in Python</em>. <a href="https://scikit-learn.org/stable/">https://scikit-learn.org/stable/</a>.
</div>
<div id="ref-Timbers_breast_cancer_repo" class="csl-entry" role="listitem">
Timbers, T. n.d. <span>“Breast-Cancer-Predictor.”</span> GitHub. <a href="https://github.com/ttimbers/breast-cancer-predictor">https://github.com/ttimbers/breast-cancer-predictor</a>.
</div>
<div id="ref-ucimlrepo_2025" class="csl-entry" role="listitem">
uci-ml-repo. 2025. <span>“Ucimlrepo: Python Package for Dataset Imports from the UCI Machine Learning Repository.”</span> GitHub. <a href="https://github.com/uci-ml-repo/ucimlrepo">https://github.com/uci-ml-repo/ucimlrepo</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>